// 会员列表
export const AGENT_LIST_GET = 'AGENT_LIST_GET';
export const AGENT_LIST_SEARCH_INIT = 'AGENT_LIST_SEARCH_INIT';
export const AGENT_LIST_INVITE_POST = 'AGENT_LIST_INVITE_POST';
export const AGENT_LIST_ADJUST_POST = 'AGENT_LIST_ADJUST_POST';
export const AGENT_LIST_BAN_POST = 'AGENT_LIST_BAN_POST';
export const AGENT_LIST_CHANGE_POST = 'AGENT_LIST_CHANGE_POST';
