export const CROWD_LIST_GET = 'CROWD_LIST_GET';
export const CROWD_LIST_SEARCH = 'CROWD_LIST_SEARCH';
export const CROWD_LIST_SILENT_GET = 'CROWD_LIST_SILENT_GET';
export const CROWD_LIST_CANCEL_SILENT_GET = 'CROWD_LIST_CANCEL_SILENT_GET';
export const CROWD_LIST_DISSOLVE_POST = 'CROWD_LIST_DISSOLVE_POST';
export const CROWD_LIST_SET_MANAGE_POST = 'CROWD_LIST_SET_MANAGE_POST';

// 新建成员
export const CROWD_CREATE_MEMBER_ADD = 'CROWD_CREATE_MEMBER_ADD';
export const CROWD_CREATE_MEMBER_DEL = 'CROWD_CREATE_MEMBER_DEL';
export const CROWD_CREATE_MEMBER_SET_MANAGE = 'CROWD_CREATE_MEMBER_SET_MANAGE';
export const CROWD_CREATE_MEMBER_LOADER_GET = 'CROWD_CREATE_MEMBER_LOADER_GET';
export const CROWD_CREATE_MEMBER_ADD_INIT = 'CROWD_CREATE_MEMBER_ADD_INIT';

// 新建素材
export const CROWD_CREATE_MATERIAL_ADD = 'CROWD_CREATE_MATERIAL_ADD';
export const CROWD_CREATE_MATERIAL_DEL = 'CROWD_CREATE_MATERIAL_DEL';
export const CROWD_CREATE_MATERIAL_INIT = 'CROWD_CREATE_MATERIAL_INIT';

// 编辑社群
export const CROWD_EDIT_MEMBER_LIST_GET = 'CROWD_EDIT_MEMBER_LIST_GET';
export const CROWD_EDIT_MEMBER_INIT = 'CROWD_EDIT_MEMBER_INIT';
export const CROWD_EDIT_MEMBER_ADD_POST = 'CROWD_EDIT_MEMBER_ADD_POST';
export const CROWD_EDIT_MEMBER_SET_POST = 'CROWD_EDIT_MEMBER_SET_POST';

export const CROWD_EDIT_MATERIAL_LIST_GET = 'CROWD_EDIT_MATERIAL_LIST_GET';
export const CROWD_EDIT_MATERIAL_ADD_POST = 'CROWD_EDIT_MATERIAL_ADD_POST';
export const CROWD_EDIT_MATERIAL_INIT = 'CROWD_EDIT_MATERIAL_INIT';

// 群发
export const CROWD_MESSAGE_GET = 'CROWD_MESSAGE_GET';
export const CROWD_MESSAGE_SEARCH = 'CROWD_MESSAGE_SEARCH';
export const CROWD_MESSAGE_SELECT = 'CROWD_MESSAGE_SELECT';
export const CROWD_MESSAGE_INIT = 'CROWD_MESSAGE_INIT';
export const CROWD_MESSAGE_SELECT_INIT = 'CROWD_MESSAGE_SELECT_INIT';

export const CROWD_CREATE_MEMBER_CHANGE_PAGE = 'CROWD_CREATE_MEMBER_CHANGE_PAGE';

export const CROWD_CREATE_MATERIAL_CHANGE_PAGE = 'CROWD_CREATE_MATERIAL_CHANGE_PAGE';