// 讲师管理
export const LIVE_LECTURER_LIST_GET = 'LIVE_LECTURER_LIST_GET';
export const LIVE_LECTURER_EDIT_POST = 'LIVE_LECTURER_EDIT_POST';
export const LIVE_LECTURER_DEL_POST = 'LIVE_LECTURER_DEL_POST';
export const LIVE_LECTURER_DETAIL_GET = 'LIVE_LECTURER_DETAIL_GET';
// 直播列表
export const LIVE_LIST_LIST_GET = 'LIVE_LIST_LIST_GET';
// 直播上下架
export const LIVE_LIST_ON_SHELVES_GET = 'LIVE_LIST_ON_SHELVES_GET';
export const LIVE_LIVE_SEARCH_INIT = 'LIVE_LIVE_SEARCH_INIT';
export const LIVE_LIVE_INIT = 'LIVE_LIVE_INIT';
// 直播新建添加
export const LIVE_ADD_ROOM_POST = 'LIVE_ADD_ROOM_POST';
// 直播编辑
export const LIVE_EDIT_ROOM_GET = 'LIVE_EDIT_ROOM_GET';
// 直播列表的权重值
export const LIVE_LIST_UPDATE_SORT_POST = 'LIVE_LIST_UPDATE_SORT_POST';
// 直播 删除直播
export const LIVE_LIST_ROOM_DEL_POST = 'LIVE_LIST_ROOM_DEL_POST';
// 直播 获取讲师列表
export const LIVE_LIST_ROOM_LECTURER_LIST_GET = 'LIVE_LIST_ROOM_LECTURER_LIST_GET';
// 直播 获取讲师简介
export const LIVE_LIST_ROOM_LECTURER_INFO_GET = 'LIVE_LIST_ROOM_LECTURER_INFO_GET';
// 直播 获取社群列表
export const LIVE_LIST_ROOM_COMMUNITY_LIST_GET = 'LIVE_LIST_ROOM_COMMUNITY_LIST_GET';
export const _LIVE_MAIN_LIST_SHARECODE_GET = '_LIVE_MAIN_LIST_SHARECODE_GET';
