
export const MATERIAL_MATERIAL_INIT = 'MATERIAL_MATERIAL_INIT';
export const MATERIAL_MATERIAL_SEARCH_INIT = 'MATERIAL_MATERIAL_SEARCH_INIT';

export const MATERIAL_SEARCH_INIT = 'MATERIAL_SEARCH_INIT';
// 获取素材列表
export const MATERIAL_LIST_GET = 'MATERIAL_LIST_GET';
// 删除 素材分类中的删除
export const MATERIAL_CATEGORY_LIST_DEL_GET =  'MATERIAL_CATEGORY_LIST_DEL_GET';
// 获取素材分类列表
export const MATERIAL_CATEGORY_LIST_GET = 'MATERIAL_CATEGORY_LIST_GET';

// 删除素材列表中的删除按钮
export const MATERIAL_LIST_DEL_GET = 'MATERIAL_LIST_DEL_GET';

// 获取素材分类下拉列表
export const MATERIAL_CATEGORY_SELECT_LIST_GET = 'MATERIAL_CATEGORY_SELECT_LIST_GET';

// 修改素材分类权重
export const MATERIAL_LIST_UPDATE_SORT_GET = 'MATERIAL_LIST_UPDATE_SORT_GET';

export const MATERIAL_ADD_POST = 'MATERIAL_ADD_POST';
export const MATERIAL_DETAIL_GET = 'MATERIAL_DETAIL_GET';

// 素材列表的弹框
export const MATERIAL_LIST_MODEL_MATERIAL_CHANGE_POST = 'MATERIAL_LIST_MODEL_MATERIAL_CHANGE_POST';
// 素材分类的所有素材弹框
export const MATERIAL_CATEGORY_MODEL_MATERIAL_LIST_POST = 'MATERIAL_CATEGORY_MODEL_MATERIAL_LIST_POST';

// 素材分类的关联社群弹框
export const MATERIAL_CATEGORY_MODEL_COMMUNITY_LIST_POST = 'MATERIAL_CATEGORY_MODEL_COMMUNITY_LIST_POST';

// 素材分类的新建分类弹窗
export const MATERIAL_CATEGORY_MODEL_ADD_CATEGORY_POST = 'MATERIAL_CATEGORY_MODEL_ADD_CATEGORY_POST';

// 全员公告 提交
export const MATERIAL_NOTICE_POST = 'MATERIAL_NOTICE_POST';

// 全员公告 获取
export const MATERIAL_NOTICE_INFO_GET = 'MATERIAL_NOTICE_INFO_GET';