export const HOME_MAIN_LIST_GET = 'HOME_MAIN_LIST_GET';
export const HOME_MEMBER_LIST_GET = 'HOME_MEMBER_LIST_GET';
export const HOME_MAIN_NOTICE_UPDATE_WEBSOCKET = 'HOME_MAIN_NOTICE_UPDATE_WEBSOCKET';
export const HOME_MEMBER_DETAIL_GET = 'HOME_MEMBER_DETAIL_GET';
export const MATERIAL_SHARE_LIST_GET = 'MATERIAL_SHARE_LIST_GET';
export const MATERIAL_SHARE_SELECT_CHANGE = 'MATERIAL_SHARE_SELECT_CHANGE';
export const HOME_MAIN_LIST_ADD_WEBSOCKET = 'HOME_MAIN_LIST_ADD_WEBSOCKET';
export const HOME_MEMBER_SEARCH_INIT = 'HOME_MEMBER_SEARCH_INIT';
export const HOME_MATERIAL_LIST_GET = 'HOME_MATERIAL_LIST_GET';
export const HOME_MEMBER_DETAIL_NO_SAY_POST = 'HOME_MEMBER_DETAIL_NO_SAY_POST';
export const HOME_MATERIAL_SEND_MATERIAL_POST = 'HOME_MATERIAL_SEND_MATERIAL_POST';
export const MATERIAL_SHARE_SELECT_CHANGE_INIT = 'MATERIAL_SHARE_SELECT_CHANGE_INIT';
// 群聊内容列表
export const HOME_CHAT_LIST_GET = 'HOME_CHAT_LIST_GET';
// 群聊websocket
export const HOME_CHAT_ACCEPT_WEBSOCKET = 'HOME_CHAT_ACCEPT_WEBSOCKET';  // 650
export const HOME_CHAT_ALL_LIVE_END_WEBSOCKET = 'HOME_CHAT_ALL_LIVE_END_WEBSOCKET'; // 650
export const HOME_CHAT_OPEN_FORBID_WEBSOCKET = 'HOME_CHAT_OPEN_FORBID_WEBSOCKET'; // 651
export const HOME_CHAT_CLOSE_FORBID_WEBSOCKET = 'HOME_CHAT_CLOSE_FORBID_WEBSOCKET'; // 652
