export const MINE_MAIN_LIST_GET = 'MINE_MAIN_LIST_GET';
export const MINE_NAME_SAVE_POST = 'MINE_NAME_SAVE_POST';
export const MINE_AVATAR_SAVE_POST = 'MINE_AVATAR_SAVE_POST';
export const MINE_COURSES_LIST_GET = 'MINE_COURSES_LIST_GET';
export const MINE_COLLECT_SEARCH_INIT = 'MINE_COLLECT_SEARCH_INIT';
export const MINE_COLLECT_LIST_GET = 'MINE_COLLECT_LIST_GET';
export const MINE_COLLECT_DEL_POST = 'MINE_COLLECT_DEL_POST';